### ISSUE TITLE
Markdown formats return an Internal Server Error

### ISSUE THREAD

**Issue by jordanbyron** [mendicant/anita#1]
http://anita.mendicantuniversity.org/mendicant/2012-05-13..2012-05-14.md

I tried checking the server logs but it seems that isn't turned on. Might have something to do with a missing gem for markdown in the `Gemfile`?

**Comment by semmons99** [comment]
The extension should be ".markdown" instead of ".md"

http://anita.mendicantuniversity.org/mendicant/2012-05-13..2012-05-14.markdown

**Comment by semmons99** [comment]
also, ".json" and ".html"

**Comment by jordanbyron** [comment]
@semmons99 gotcha. Is there a way to have Sinatra return a 404 rather than 500 when it doesn't know how to respond to the requested format?

**Comment by semmons99** [comment]
@jordanbyron: what do you think about this https://github.com/mendicant/anita/pull/4?

**Comment by jordanbyron** [comment]
@semmons99 looks perfectly sane to me, plus I love that we get to drop a gem dependency and move that format case statement into the `get` block which is where I'd expect it to be :shipit:
